# Setup
title:        Edge-Device Large Language Model Competition
tagline:      NeurIPS 2024 Challenge
baseurl:      "/edge-llms-challenge.github.io"
paginate:     1
locale:       "en"

# About/contact
author:
  #name:       Author name
  url:       "https://adrianafernandez02.github.io" 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown